// GENERATED by tools/gen-n3-types.mjs — do not edit.
// Port/output metadata for the NodeBox 3 standard libraries, extracted
// from the official .ndbx library files (github.com/nodebox/nodebox,
// GPLv2). Implementations live in n3lib.js and are matched via `fn`.

export const N3_TYPE_DEFS = [
 {
  "id": "math.abs",
  "name": "abs",
  "category": "math",
  "description": "Convert every number to a positive number.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/abs",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.add",
  "name": "add",
  "category": "math",
  "description": "Add two numbers.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/add",
  "ports": [
   {
    "name": "value1",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "value2",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.angle",
  "name": "angle",
  "category": "math",
  "description": "Calculate the angle between two points.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/angle",
  "ports": [
   {
    "name": "point1",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "widget": "point"
   },
   {
    "name": "point2",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 100,
     "y": 100
    },
    "widget": "point"
   }
  ]
 },
 {
  "id": "math.average",
  "name": "average",
  "category": "math",
  "description": "Calculate the average of a list of numbers.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/average",
  "ports": [
   {
    "name": "values",
    "type": "float",
    "n3Type": "float",
    "range": "list",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.boolean",
  "name": "boolean",
  "category": "math",
  "description": "Create a boolean value that can be used as a variable.",
  "outputType": "boolean",
  "outputRange": "value",
  "fn": "math/makeBoolean",
  "ports": [
   {
    "name": "value",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": false,
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "math.ceil",
  "name": "ceil",
  "category": "math",
  "description": "Round up the value of a number.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/ceil",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.compare",
  "name": "compare",
  "category": "math",
  "description": "Select between two values by comparing them.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/compare",
  "ports": [
   {
    "name": "value1",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "value2",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "comparator",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "<",
    "widget": "menu",
    "menu": [
     {
      "key": "<",
      "label": "< less than"
     },
     {
      "key": ">",
      "label": "> greater than"
     },
     {
      "key": "<=",
      "label": "<= less than or equal to"
     },
     {
      "key": ">=",
      "label": ">= greater than or equal to"
     },
     {
      "key": "==",
      "label": "== equal"
     },
     {
      "key": "!=",
      "label": "!= not equal"
     }
    ]
   }
  ]
 },
 {
  "id": "math.logical",
  "name": "logical",
  "category": "math",
  "description": "Create a logical or operator.",
  "outputType": "boolean",
  "outputRange": "value",
  "fn": "math/logicOperator",
  "ports": [
   {
    "name": "boolean1",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": false,
    "widget": "toggle"
   },
   {
    "name": "boolean2",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": false,
    "widget": "toggle"
   },
   {
    "name": "comparator",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "or",
    "widget": "menu",
    "menu": [
     {
      "key": "or",
      "label": "OR"
     },
     {
      "key": "and",
      "label": "AND"
     },
     {
      "key": "xor",
      "label": "XOR"
     }
    ]
   }
  ]
 },
 {
  "id": "math.convert_range",
  "name": "convert_range",
  "category": "math",
  "description": "Convert a value from one range to another.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/convertRange",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 50,
    "widget": "float"
   },
   {
    "name": "source_start",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "source_end",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "widget": "float"
   },
   {
    "name": "target_start",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "target_end",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 1,
    "widget": "float"
   },
   {
    "name": "method",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "clamp",
    "widget": "menu",
    "menu": [
     {
      "key": "mirror",
      "label": "Mirror"
     },
     {
      "key": "ignore",
      "label": "Ignore"
     },
     {
      "key": "wrap",
      "label": "Wrap"
     },
     {
      "key": "clamp",
      "label": "Clamp"
     }
    ]
   }
  ]
 },
 {
  "id": "math.coordinates",
  "name": "coordinates",
  "category": "math",
  "description": "Calculate a new point based on the angle and distance from an original point.",
  "outputType": "point",
  "outputRange": "value",
  "fn": "math/coordinates",
  "ports": [
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "widget": "point"
   },
   {
    "name": "angle",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "distance",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.cos",
  "name": "cos",
  "category": "math",
  "description": "Calculate the trigonometric cosine of an angle.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/cos",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.degrees",
  "name": "degrees",
  "category": "math",
  "description": "Convert radians to degrees.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/degrees",
  "ports": [
   {
    "name": "radians",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.distance",
  "name": "distance",
  "category": "math",
  "description": "Calculate the distance between two points.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/distance",
  "ports": [
   {
    "name": "point1",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "widget": "point"
   },
   {
    "name": "point2",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 100,
     "y": 100
    },
    "widget": "point"
   }
  ]
 },
 {
  "id": "math.divide",
  "name": "divide",
  "category": "math",
  "description": "Divide two numbers.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/divide",
  "ports": [
   {
    "name": "value1",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "value2",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 1,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.e",
  "name": "e",
  "category": "math",
  "description": "The value of the mathematical constant e, the base of the natural logarithm.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/e",
  "ports": []
 },
 {
  "id": "math.even",
  "name": "even",
  "category": "math",
  "description": "Determine if a number is even.",
  "outputType": "boolean",
  "outputRange": "value",
  "fn": "math/even",
  "ports": [
   {
    "name": "value",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "widget": "int"
   }
  ]
 },
 {
  "id": "math.floor",
  "name": "floor",
  "category": "math",
  "description": "Round down the value of a number.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/floor",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.integer",
  "name": "integer",
  "category": "math",
  "description": "Create an integer value that can be used as a variable.",
  "outputType": "int",
  "outputRange": "value",
  "fn": "math/integer",
  "ports": [
   {
    "name": "value",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "widget": "int"
   }
  ]
 },
 {
  "id": "math.log",
  "name": "log",
  "category": "math",
  "description": "Calculate the natural logarithm of a value.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/log",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 1,
    "min": 0.01,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.make_numbers",
  "name": "make_numbers",
  "category": "math",
  "description": "Transform a string to a list of numbers.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "math/makeNumbers",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "11;22;33",
    "widget": "string"
   },
   {
    "name": "separator",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": ";",
    "widget": "string"
   }
  ]
 },
 {
  "id": "math.max",
  "name": "max",
  "category": "math",
  "description": "Select the largest value from a list of numbers.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/max",
  "ports": [
   {
    "name": "values",
    "type": "float",
    "n3Type": "float",
    "range": "list",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.min",
  "name": "min",
  "category": "math",
  "description": "Select the smallest value from a list of numbers.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/min",
  "ports": [
   {
    "name": "values",
    "type": "float",
    "n3Type": "float",
    "range": "list",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.mod",
  "name": "mod",
  "category": "math",
  "description": "Calculate the modulo by dividing two numbers and keeping the remainder.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/mod",
  "ports": [
   {
    "name": "value1",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "value2",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 1,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.multiply",
  "name": "multiply",
  "category": "math",
  "description": "Multiply two numbers.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/multiply",
  "ports": [
   {
    "name": "value1",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "value2",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 1,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.negate",
  "name": "negate",
  "category": "math",
  "description": "Change the sign of a number by negating it.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/negate",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.number",
  "name": "number",
  "category": "math",
  "description": "Create a floating-point value that can be used as a variable.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/number",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.odd",
  "name": "odd",
  "category": "math",
  "description": "Determine if a number is odd.",
  "outputType": "boolean",
  "outputRange": "value",
  "fn": "math/odd",
  "ports": [
   {
    "name": "value",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "widget": "int"
   }
  ]
 },
 {
  "id": "math.pi",
  "name": "pi",
  "category": "math",
  "description": "The value of the mathematical constant pi.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/pi",
  "ports": []
 },
 {
  "id": "math.pow",
  "name": "pow",
  "category": "math",
  "description": "Calculate the power of a number.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/pow",
  "ports": [
   {
    "name": "value1",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "value2",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.radians",
  "name": "radians",
  "category": "math",
  "description": "Convert degrees to radians.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/radians",
  "ports": [
   {
    "name": "degrees",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.random_numbers",
  "name": "random_numbers",
  "category": "math",
  "description": "Create a list of random numbers.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "math/randomNumbers",
  "ports": [
   {
    "name": "amount",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 10,
    "min": 0,
    "widget": "int"
   },
   {
    "name": "start",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "end",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "widget": "float"
   },
   {
    "name": "seed",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "widget": "int"
   }
  ]
 },
 {
  "id": "math.range",
  "name": "range",
  "category": "math",
  "description": "Generate a range of numbers.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "math/range",
  "ports": [
   {
    "name": "start",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "end",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 10,
    "widget": "float"
   },
   {
    "name": "step",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 1,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.reflect",
  "name": "reflect",
  "category": "math",
  "description": "Calculate a new point based on the angle and distance from an original point.",
  "outputType": "point",
  "outputRange": "value",
  "fn": "math/reflect",
  "ports": [
   {
    "name": "point1",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "widget": "point"
   },
   {
    "name": "point2",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 100,
     "y": 100
    },
    "widget": "point"
   },
   {
    "name": "angle",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "distance",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 1,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.round",
  "name": "round",
  "category": "math",
  "description": "Convert a floating-point number to an integer.",
  "outputType": "int",
  "outputRange": "value",
  "fn": "math/round",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.running_total",
  "name": "running_total",
  "category": "math",
  "description": "Generate in between totals of a list of numbers.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "math/runningTotal",
  "ports": [
   {
    "name": "values",
    "type": "float",
    "n3Type": "float",
    "range": "list",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.sample",
  "name": "sample",
  "category": "math",
  "description": "Generate numbers within the given bounds.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "math/sample",
  "ports": [
   {
    "name": "amount",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 10,
    "min": 0,
    "widget": "int"
   },
   {
    "name": "start",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "end",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.sin",
  "name": "sin",
  "category": "math",
  "description": "Calculate the trigonometric sine of an angle.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/sin",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.sqrt",
  "name": "sqrt",
  "category": "math",
  "description": "Calculate the square root of a number.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/sqrt",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.subtract",
  "name": "subtract",
  "category": "math",
  "description": "Subtract two numbers.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/subtract",
  "ports": [
   {
    "name": "value1",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "value2",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.sum",
  "name": "sum",
  "category": "math",
  "description": "Add up all numbers in the list.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/sum",
  "ports": [
   {
    "name": "values",
    "type": "float",
    "n3Type": "float",
    "range": "list",
    "value": 0,
    "widget": "float"
   }
  ]
 },
 {
  "id": "math.wave",
  "name": "wave",
  "category": "math",
  "description": "Calculate a value based on wave equations.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "math/wave",
  "ports": [
   {
    "name": "min",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "max",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "widget": "float"
   },
   {
    "name": "period",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 60,
    "widget": "float"
   },
   {
    "name": "offset",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "type",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "sine",
    "widget": "menu",
    "menu": [
     {
      "key": "sine",
      "label": "Sine"
     },
     {
      "key": "square",
      "label": "Square"
     },
     {
      "key": "triangle",
      "label": "Triangle"
     },
     {
      "key": "sawtooth",
      "label": "Sawtooth"
     }
    ]
   }
  ]
 },
 {
  "id": "list.combine",
  "name": "combine",
  "category": "list",
  "description": "Combine multiple lists into one.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/combine",
  "ports": [
   {
    "name": "list1",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The first list."
   },
   {
    "name": "list2",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The second list."
   },
   {
    "name": "list3",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The third list."
   },
   {
    "name": "list4",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The fourth list."
   },
   {
    "name": "list5",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The fifth list."
   },
   {
    "name": "list6",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The sixth list."
   },
   {
    "name": "list7",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The seventh list."
   }
  ]
 },
 {
  "id": "list.count",
  "name": "count",
  "category": "list",
  "description": "Count the number of items in the list.",
  "outputType": "int",
  "outputRange": "value",
  "fn": "list/count",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   }
  ]
 },
 {
  "id": "list.cull",
  "name": "cull",
  "category": "list",
  "description": "Remove all items from the list where the corresponding boolean is false.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/cull",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   },
   {
    "name": "booleans",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "A list of matching boolean values. All list items where the booleans are true will be retained."
   }
  ]
 },
 {
  "id": "list.distinct",
  "name": "distinct",
  "category": "list",
  "description": "Remove all duplicate items from the list.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/distinct",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   },
   {
    "name": "key",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "description": "An optional lookup key that will be searched for distinct values.",
    "widget": "string"
   }
  ]
 },
 {
  "id": "list.first",
  "name": "first",
  "category": "list",
  "description": "Take the first item of the list.",
  "outputType": "list",
  "outputRange": "value",
  "fn": "list/first",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   }
  ]
 },
 {
  "id": "list.keys",
  "name": "keys",
  "category": "list",
  "description": "Take the keys of a map.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/keys",
  "ports": [
   {
    "name": "maps",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input map."
   }
  ]
 },
 {
  "id": "list.last",
  "name": "last",
  "category": "list",
  "description": "Take the last item of the list.",
  "outputType": "list",
  "outputRange": "value",
  "fn": "list/last",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   }
  ]
 },
 {
  "id": "list.pick",
  "name": "pick",
  "category": "list",
  "description": "Pick items from the list in random order.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/pick",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   },
   {
    "name": "amount",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 5,
    "description": "The amount of items to pick.",
    "widget": "int"
   },
   {
    "name": "seed",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "description": "The random variation.",
    "widget": "int"
   }
  ]
 },
 {
  "id": "list.repeat",
  "name": "repeat",
  "category": "list",
  "description": "Repeat the list a number of times.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/repeat",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   },
   {
    "name": "amount",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 1,
    "description": "The amount of times to repeat the list.",
    "widget": "int"
   },
   {
    "name": "per_item",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": false,
    "description": "Repeat items one after another.",
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "list.rest",
  "name": "rest",
  "category": "list",
  "description": "Take all but the first item of the list.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/rest",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   }
  ]
 },
 {
  "id": "list.reverse",
  "name": "reverse",
  "category": "list",
  "description": "Reverse the list.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/reverse",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   }
  ]
 },
 {
  "id": "list.second",
  "name": "second",
  "category": "list",
  "description": "Take the second item of the list.",
  "outputType": "list",
  "outputRange": "value",
  "fn": "list/second",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   }
  ]
 },
 {
  "id": "list.shift",
  "name": "shift",
  "category": "list",
  "description": "Move items at the beginning of the list to the end.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/shift",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   },
   {
    "name": "amount",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 1,
    "description": "The number of items to shift.",
    "widget": "int"
   }
  ]
 },
 {
  "id": "list.shuffle",
  "name": "shuffle",
  "category": "list",
  "description": "Randomize the ordering of items in the list.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/shuffle",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   },
   {
    "name": "seed",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "description": "The random variation.",
    "widget": "int"
   }
  ]
 },
 {
  "id": "list.slice",
  "name": "slice",
  "category": "list",
  "description": "Take a portion of the list.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/slice",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   },
   {
    "name": "start_index",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "min": 0,
    "description": "The starting index in the list.",
    "widget": "int"
   },
   {
    "name": "size",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 10,
    "min": 0,
    "description": "The amount of items to take from the list.",
    "widget": "int"
   },
   {
    "name": "invert",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "description": "Omit the items instead of retaining them."
   }
  ]
 },
 {
  "id": "list.sort",
  "name": "sort",
  "category": "list",
  "description": "Sort items in the list.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/sort",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   },
   {
    "name": "key",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "description": "The key used to compare and sort the items.",
    "widget": "string"
   }
  ]
 },
 {
  "id": "list.switch",
  "name": "switch",
  "category": "list",
  "description": "Switch between multiple inputs.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "list/doSwitch",
  "ports": [
   {
    "name": "input1",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The first list."
   },
   {
    "name": "input2",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The second list."
   },
   {
    "name": "input3",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The third list."
   },
   {
    "name": "input4",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The fourth list."
   },
   {
    "name": "input5",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The fifth list."
   },
   {
    "name": "input6",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The sixth list."
   },
   {
    "name": "index",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "description": "The index of the input list to select. If the index is greater than the number of inputs, it wraps around.",
    "widget": "int"
   }
  ]
 },
 {
  "id": "list.take_every",
  "name": "take_every",
  "category": "list",
  "description": "Take every nth element of the list.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "list/takeEvery",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The input list."
   },
   {
    "name": "n",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 1,
    "min": 1,
    "description": "The amount of items to skip.",
    "widget": "int"
   }
  ]
 },
 {
  "id": "list.zip_map",
  "name": "zip_map",
  "category": "list",
  "description": "Combine a list of keys and values together into a map.",
  "outputType": "list",
  "outputRange": "value",
  "fn": "list/zipMap",
  "ports": [
   {
    "name": "keys",
    "type": "string",
    "n3Type": "string",
    "range": "list",
    "description": "A list of keys."
   },
   {
    "name": "values",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "A list of values."
   }
  ]
 },
 {
  "id": "string.as_binary_list",
  "name": "as_binary_list",
  "category": "string",
  "description": "Convert a string into its binary representation",
  "outputType": "string",
  "outputRange": "list",
  "fn": "string/asBinaryList",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.as_binary_string",
  "name": "as_binary_string",
  "category": "string",
  "description": "Convert a string into its binary representation",
  "outputType": "string",
  "outputRange": "value",
  "fn": "string/asBinaryString",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   },
   {
    "name": "digit_separator",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "widget": "string"
   },
   {
    "name": "byte_separator",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": " ",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.as_number_list",
  "name": "as_number_list",
  "category": "string",
  "description": "Convert a string into a numeric encoding",
  "outputType": "string",
  "outputRange": "list",
  "fn": "string/asNumberList",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   },
   {
    "name": "radix",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 10,
    "min": 2,
    "max": 21,
    "widget": "int"
   },
   {
    "name": "padding",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": true,
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "string.change_case",
  "name": "change_case",
  "category": "string",
  "description": "Change a string into upper, lower or title case.",
  "outputType": "string",
  "outputRange": "value",
  "fn": "string/changeCase",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   },
   {
    "name": "method",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "uppercase",
    "widget": "menu",
    "menu": [
     {
      "key": "lowercase",
      "label": "Lower Case"
     },
     {
      "key": "uppercase",
      "label": "Upper Case"
     },
     {
      "key": "titlecase",
      "label": "Title Case"
     }
    ]
   }
  ]
 },
 {
  "id": "string.character_at",
  "name": "character_at",
  "category": "string",
  "description": "Output the character at a given index",
  "outputType": "string",
  "outputRange": "list",
  "fn": "string/characterAt",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   },
   {
    "name": "index",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "widget": "int"
   }
  ]
 },
 {
  "id": "string.characters",
  "name": "characters",
  "category": "string",
  "description": "Create a list of characters from a string",
  "outputType": "string",
  "outputRange": "list",
  "fn": "string/characters",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.concatenate",
  "name": "concatenate",
  "category": "string",
  "description": "Add strings together.",
  "outputType": "string",
  "outputRange": "value",
  "fn": "string/concatenate",
  "ports": [
   {
    "name": "string1",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "widget": "string"
   },
   {
    "name": "string2",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "widget": "string"
   },
   {
    "name": "string3",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "widget": "string"
   },
   {
    "name": "string4",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "widget": "string"
   },
   {
    "name": "string5",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "widget": "string"
   },
   {
    "name": "string6",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "widget": "string"
   },
   {
    "name": "string7",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.contains",
  "name": "contains",
  "category": "string",
  "description": "Determine if the string contains a given string",
  "outputType": "boolean",
  "outputRange": "value",
  "fn": "string/contains",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   },
   {
    "name": "contains",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "efa",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.ends_with",
  "name": "ends_with",
  "category": "string",
  "description": "Determine if the string ends with a given string",
  "outputType": "boolean",
  "outputRange": "value",
  "fn": "string/endsWith",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   },
   {
    "name": "ends_with",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "lt",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.equals",
  "name": "equals",
  "category": "string",
  "description": "Determine if the string equals a given string",
  "outputType": "boolean",
  "outputRange": "value",
  "fn": "string/equal",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   },
   {
    "name": "equals",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   },
   {
    "name": "case_sensitive",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": false,
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "string.format_number",
  "name": "format_number",
  "category": "string",
  "description": "Represent a numeric value as a string in a specific way.",
  "outputType": "string",
  "outputRange": "value",
  "fn": "string/formatNumber",
  "ports": [
   {
    "name": "value",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "format",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "%.2f",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.length",
  "name": "length",
  "category": "string",
  "description": "Count the number of characters in a string.",
  "outputType": "int",
  "outputRange": "value",
  "fn": "string/length",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.make_strings",
  "name": "make_strings",
  "category": "string",
  "description": "Create a list of strings.",
  "outputType": "string",
  "outputRange": "list",
  "fn": "string/makeStrings",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "Alpha;Beta;Gamma",
    "widget": "string"
   },
   {
    "name": "separator",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": ";",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.random_character",
  "name": "random_character",
  "category": "string",
  "description": "Create a list of random characters taken from a set",
  "outputType": "string",
  "outputRange": "list",
  "fn": "string/randomCharacter",
  "ports": [
   {
    "name": "characters",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
    "widget": "string"
   },
   {
    "name": "amount",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 10,
    "min": 0,
    "widget": "int"
   },
   {
    "name": "seed",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "widget": "int"
   }
  ]
 },
 {
  "id": "string.replace",
  "name": "replace",
  "category": "string",
  "description": "Replace part of a string",
  "outputType": "string",
  "outputRange": "value",
  "fn": "string/replace",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "defAULt",
    "widget": "string"
   },
   {
    "name": "old",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "AUL",
    "widget": "string"
   },
   {
    "name": "new",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "aul",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.starts_with",
  "name": "starts_with",
  "category": "string",
  "description": "Determine if the string starts with a given string",
  "outputType": "boolean",
  "outputRange": "value",
  "fn": "string/startsWith",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   },
   {
    "name": "starts_with",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "def",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.string",
  "name": "string",
  "category": "string",
  "description": "Create a string value that can be used as a variable.",
  "outputType": "string",
  "outputRange": "value",
  "fn": "string/string",
  "ports": [
   {
    "name": "value",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.sub_string",
  "name": "sub_string",
  "category": "string",
  "description": "Take a portion of a string",
  "outputType": "string",
  "outputRange": "value",
  "fn": "string/subString",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "default",
    "widget": "string"
   },
   {
    "name": "start",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "widget": "int"
   },
   {
    "name": "end",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 4,
    "widget": "int"
   },
   {
    "name": "end_offset",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": false,
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "string.trim",
  "name": "trim",
  "category": "string",
  "description": "Remove white space from the start and end",
  "outputType": "string",
  "outputRange": "value",
  "fn": "string/trim",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "  def  au lt  ",
    "widget": "string"
   }
  ]
 },
 {
  "id": "string.word_count",
  "name": "word_count",
  "category": "string",
  "description": "Count the number of words in a string.",
  "outputType": "int",
  "outputRange": "value",
  "fn": "string/wordCount",
  "ports": [
   {
    "name": "string",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "widget": "string"
   }
  ]
 },
 {
  "id": "color.color",
  "name": "color",
  "category": "color",
  "description": "Create a color value that can be used as a variable.",
  "outputType": "color",
  "outputRange": "value",
  "fn": "color/color",
  "ports": [
   {
    "name": "color",
    "type": "color",
    "n3Type": "color",
    "range": "value",
    "value": {
     "r": 0,
     "g": 0,
     "b": 0,
     "a": 1
    },
    "widget": "color"
   }
  ]
 },
 {
  "id": "color.gray_color",
  "name": "gray_color",
  "category": "color",
  "description": "Create a gray color.",
  "outputType": "color",
  "outputRange": "value",
  "fn": "color/gray",
  "ports": [
   {
    "name": "gray",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "alpha",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 255,
    "widget": "float"
   },
   {
    "name": "range",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 255,
    "widget": "float"
   }
  ]
 },
 {
  "id": "color.hsb_color",
  "name": "hsb_color",
  "category": "color",
  "description": "Create a HSB color.",
  "outputType": "color",
  "outputRange": "value",
  "fn": "color/hsb",
  "ports": [
   {
    "name": "hue",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "saturation",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "brightness",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "alpha",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 255,
    "widget": "float"
   },
   {
    "name": "range",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 255,
    "widget": "float"
   }
  ]
 },
 {
  "id": "color.rgb_color",
  "name": "rgb_color",
  "category": "color",
  "description": "Create a RGB color.",
  "outputType": "color",
  "outputRange": "value",
  "fn": "color/rgb",
  "ports": [
   {
    "name": "red",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "green",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "blue",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "widget": "float"
   },
   {
    "name": "alpha",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 255,
    "widget": "float"
   },
   {
    "name": "range",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 255,
    "widget": "float"
   }
  ]
 },
 {
  "id": "data.import_text",
  "name": "import_text",
  "category": "data",
  "description": "Import a text file and return each line of the file.",
  "outputType": "string",
  "outputRange": "list",
  "fn": "data/importText",
  "ports": [
   {
    "name": "file",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "description": "The text file.",
    "widget": "file"
   }
  ]
 },
 {
  "id": "data.import_csv",
  "name": "import_csv",
  "category": "data",
  "description": "Import a comma-separated value file containing tabular data.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "data/importCSV",
  "ports": [
   {
    "name": "file",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "description": "The CSV file.",
    "widget": "file"
   },
   {
    "name": "delimiter",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "comma",
    "description": "The character used to separate columns.",
    "widget": "menu",
    "menu": [
     {
      "key": "comma",
      "label": ","
     },
     {
      "key": "semicolon",
      "label": ";"
     },
     {
      "key": "colon",
      "label": ":"
     },
     {
      "key": "tab",
      "label": "Tab"
     },
     {
      "key": "space",
      "label": "Space"
     }
    ]
   },
   {
    "name": "quotes",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "double",
    "description": "The type of quotes used in the file.",
    "widget": "menu",
    "menu": [
     {
      "key": "double",
      "label": "\""
     },
     {
      "key": "single",
      "label": "'"
     }
    ]
   },
   {
    "name": "number_separator",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "period",
    "description": "The character used to separate the fractional part.",
    "widget": "menu",
    "menu": [
     {
      "key": "period",
      "label": "."
     },
     {
      "key": "comma",
      "label": ","
     }
    ]
   }
  ]
 },
 {
  "id": "data.make_table",
  "name": "make_table",
  "category": "data",
  "description": "Make a data table out of lists.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "data/makeTable",
  "ports": [
   {
    "name": "headers",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "alpha;beta",
    "description": "The names of the headers separated by semicolons or commas."
   },
   {
    "name": "list1",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The first list."
   },
   {
    "name": "list2",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The second list."
   },
   {
    "name": "list3",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The third list."
   },
   {
    "name": "list4",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The fourth list."
   },
   {
    "name": "list5",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The fifth list."
   },
   {
    "name": "list6",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The sixth list."
   }
  ]
 },
 {
  "id": "data.lookup",
  "name": "lookup",
  "category": "data",
  "description": "Look up a value in a table or object.",
  "outputType": "list",
  "outputRange": "value",
  "fn": "data/lookup",
  "ports": [
   {
    "name": "list",
    "type": "list",
    "n3Type": "list",
    "range": "value",
    "description": "The input value."
   },
   {
    "name": "key",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "x",
    "description": "The key to lookup.",
    "widget": "string"
   }
  ]
 },
 {
  "id": "data.filter_data",
  "name": "filter_data",
  "category": "data",
  "description": "Filter the data based on key/value.",
  "outputType": "list",
  "outputRange": "list",
  "fn": "data/filterData",
  "ports": [
   {
    "name": "data",
    "type": "list",
    "n3Type": "data",
    "range": "list"
   },
   {
    "name": "key",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "name",
    "widget": "string"
   },
   {
    "name": "op",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "=",
    "widget": "menu",
    "menu": [
     {
      "key": "=",
      "label": "= Equal To"
     },
     {
      "key": "!=",
      "label": "!= Not Equal To"
     },
     {
      "key": ">",
      "label": "> Greater Than"
     },
     {
      "key": ">=",
      "label": ">= Greater or Equal Than"
     },
     {
      "key": "<",
      "label": "< Smaller Than"
     },
     {
      "key": "<=",
      "label": "<= Smaller or Equal Than"
     }
    ]
   },
   {
    "name": "value",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "Bob",
    "widget": "string"
   }
  ]
 },
 {
  "id": "corevector.generator",
  "name": "generator",
  "category": "corevector",
  "description": "Template for creating nodes that generate vector data.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/generator",
  "ports": []
 },
 {
  "id": "corevector.filter",
  "name": "filter",
  "category": "corevector",
  "description": "Template for creating nodes that manipulate vector data.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/filter",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   }
  ]
 },
 {
  "id": "corevector.align",
  "name": "align",
  "category": "corevector",
  "description": "Align a shape in relation to the origin.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/align",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The alignment point.",
    "widget": "point"
   },
   {
    "name": "halign",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "center",
    "label": "Horizontal Align",
    "description": "The horizontal alignment.",
    "widget": "menu",
    "menu": [
     {
      "key": "none",
      "label": "No Change"
     },
     {
      "key": "left",
      "label": "Left"
     },
     {
      "key": "center",
      "label": "Center"
     },
     {
      "key": "right",
      "label": "Right"
     }
    ]
   },
   {
    "name": "valign",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "middle",
    "label": "Vertical Align",
    "description": "The vertical alignment.",
    "widget": "menu",
    "menu": [
     {
      "key": "none",
      "label": "No Change"
     },
     {
      "key": "top",
      "label": "Top"
     },
     {
      "key": "middle",
      "label": "Middle"
     },
     {
      "key": "bottom",
      "label": "Bottom"
     }
    ]
   }
  ]
 },
 {
  "id": "corevector.arc",
  "name": "arc",
  "category": "corevector",
  "description": "Create an arc.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/arc",
  "ports": [
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The center point of the arc.",
    "widget": "point"
   },
   {
    "name": "width",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "description": "The width of the arc.",
    "widget": "float"
   },
   {
    "name": "height",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "description": "The height of the arc.",
    "widget": "float"
   },
   {
    "name": "start_angle",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "description": "The starting angle of the arc. 0 degrees is at 3 o'clock.",
    "widget": "float"
   },
   {
    "name": "degrees",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 45,
    "description": "The amount of degrees of the arc.",
    "widget": "float"
   },
   {
    "name": "type",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "pie",
    "description": "The type of arc: pie, chord or open.",
    "widget": "menu",
    "menu": [
     {
      "key": "pie",
      "label": "Pie"
     },
     {
      "key": "chord",
      "label": "Chord"
     },
     {
      "key": "open",
      "label": "Open"
     }
    ]
   }
  ]
 },
 {
  "id": "corevector.centroid",
  "name": "centroid",
  "category": "corevector",
  "description": "Calculate the geometric center point of a shape.",
  "outputType": "point",
  "outputRange": "value",
  "fn": "corevector/centroid",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   }
  ]
 },
 {
  "id": "corevector.colorize",
  "name": "colorize",
  "category": "corevector",
  "description": "Change the color of a shape.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/colorize",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "fill",
    "type": "color",
    "n3Type": "color",
    "range": "value",
    "value": {
     "r": 0,
     "g": 0,
     "b": 0,
     "a": 1
    },
    "description": "The new fill color. Set alpha to 0 for no fill.",
    "widget": "color"
   },
   {
    "name": "stroke",
    "type": "color",
    "n3Type": "color",
    "range": "value",
    "value": {
     "r": 0,
     "g": 0,
     "b": 0,
     "a": 1
    },
    "description": "The new stroke color.",
    "widget": "color"
   },
   {
    "name": "strokeWidth",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "min": 0,
    "label": "Stroke Width",
    "description": "The new stroke width. Set to 0 for no stroke.",
    "widget": "float"
   }
  ]
 },
 {
  "id": "corevector.compound",
  "name": "compound",
  "category": "corevector",
  "description": "Add, subtract or intersect geometry.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/compound",
  "ports": [
   {
    "name": "shape1",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The first shape."
   },
   {
    "name": "shape2",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The second shape."
   },
   {
    "name": "function",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "united",
    "description": "The method to use for combining the shapes.",
    "widget": "menu",
    "menu": [
     {
      "key": "united",
      "label": "Union"
     },
     {
      "key": "subtracted",
      "label": "Difference"
     },
     {
      "key": "intersected",
      "label": "Intersection"
     }
    ]
   },
   {
    "name": "invert_difference",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": false,
    "description": "Switch shape1 and shape2 internally.",
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "corevector.connect",
  "name": "connect",
  "category": "corevector",
  "description": "Connect all points in a path.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/connect",
  "ports": [
   {
    "name": "points",
    "type": "list",
    "n3Type": "list",
    "range": "list",
    "description": "The list of points to connect."
   },
   {
    "name": "closed",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": true,
    "description": "If true, closes the shape. This has an effect on the path stroke.",
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "corevector.copy",
  "name": "copy",
  "category": "corevector",
  "description": "Create multiple copies of a shape.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "corevector/copy",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "copies",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 1,
    "min": 1,
    "description": "The amount of copies.",
    "widget": "int"
   },
   {
    "name": "order",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "tsr",
    "description": "The order in which to perform translation, rotation and scale.",
    "widget": "menu",
    "menu": [
     {
      "key": "srt",
      "label": "Scale Rot Trans"
     },
     {
      "key": "str",
      "label": "Scale Trans Rot"
     },
     {
      "key": "rst",
      "label": "Rot Scale Trans"
     },
     {
      "key": "rtr",
      "label": "Rot Trans Scale"
     },
     {
      "key": "tsr",
      "label": "Trans Scale Rot"
     },
     {
      "key": "trs",
      "label": "Trans Rot Scale"
     }
    ]
   },
   {
    "name": "translate",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The amount to move each copy.",
    "widget": "point"
   },
   {
    "name": "rotate",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "description": "The amount to rotate each copy.",
    "widget": "float"
   },
   {
    "name": "scale",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 100,
     "y": 100
    },
    "description": "The amount to scale each copy.",
    "widget": "point"
   }
  ]
 },
 {
  "id": "corevector.delete",
  "name": "delete",
  "category": "corevector",
  "description": "Delete points or paths that lie within the given bounding shape.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/delete",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "bounding",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The bounding shape."
   },
   {
    "name": "scope",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "points",
    "description": "Whether to delete points or paths.",
    "widget": "menu",
    "menu": [
     {
      "key": "points",
      "label": "Points"
     },
     {
      "key": "paths",
      "label": "Paths"
     }
    ]
   },
   {
    "name": "operation",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "selected",
    "description": "Whether to delete the selected or non-selected points or paths.",
    "widget": "menu",
    "menu": [
     {
      "key": "selected",
      "label": "Delete Selected"
     },
     {
      "key": "non-selected",
      "label": "Delete Non-selected"
     }
    ]
   }
  ]
 },
 {
  "id": "corevector.distribute",
  "name": "distribute",
  "category": "corevector",
  "description": "Distribute shapes on a horizontal or vertical axis.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "pyvector/distribute",
  "ports": [
   {
    "name": "shapes",
    "type": "shape",
    "n3Type": "geometry",
    "range": "list",
    "description": "The list of shapes to distribute."
   },
   {
    "name": "horizontal",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "none",
    "description": "The method of horizontal distribution.",
    "widget": "menu",
    "menu": [
     {
      "key": "none",
      "label": "No Change"
     },
     {
      "key": "left",
      "label": "Left"
     },
     {
      "key": "center",
      "label": "Center"
     },
     {
      "key": "right",
      "label": "Right"
     }
    ]
   },
   {
    "name": "vertical",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "none",
    "description": "The method of vertical distribution.",
    "widget": "menu",
    "menu": [
     {
      "key": "none",
      "label": "No Change"
     },
     {
      "key": "top",
      "label": "Top"
     },
     {
      "key": "middle",
      "label": "Middle"
     },
     {
      "key": "bottom",
      "label": "Bottom"
     }
    ]
   }
  ]
 },
 {
  "id": "corevector.ellipse",
  "name": "ellipse",
  "category": "corevector",
  "description": "Create an ellipse or circle.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/ellipse",
  "ports": [
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The center point of the ellipse.",
    "widget": "point"
   },
   {
    "name": "width",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "description": "The width of the ellipse.",
    "widget": "float"
   },
   {
    "name": "height",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "description": "The height of the ellipse.",
    "widget": "float"
   }
  ]
 },
 {
  "id": "corevector.fit",
  "name": "fit",
  "category": "corevector",
  "description": "Fit a shape within bounds.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/fit",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The target center point of the shape.",
    "widget": "point"
   },
   {
    "name": "width",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 300,
    "description": "The maximum target width of the shape.",
    "widget": "float"
   },
   {
    "name": "height",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 300,
    "description": "The maximum target height of the shape.",
    "widget": "float"
   },
   {
    "name": "keep_proportions",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": true,
    "description": "If true, does not squash or stretch the shape.",
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "corevector.fit_to",
  "name": "fit_to",
  "category": "corevector",
  "description": "Fit a shape to another shape.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/fitTo",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "bounding",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The bounding shape to take position, width and height from."
   },
   {
    "name": "keep_proportions",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": true,
    "description": "If true, does not squash or stretch the shape.",
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "corevector.freehand",
  "name": "freehand",
  "category": "corevector",
  "description": "Draw directly on the canvas using the mouse.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/freehand",
  "ports": [
   {
    "name": "path",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "description": "The internal path data.",
    "widget": "data"
   }
  ]
 },
 {
  "id": "corevector.grid",
  "name": "grid",
  "category": "corevector",
  "description": "Create a grid of points.",
  "outputType": "point",
  "outputRange": "list",
  "fn": "corevector/grid",
  "ports": [
   {
    "name": "columns",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 10,
    "min": 1,
    "description": "The amount of columns in the grid.",
    "widget": "int"
   },
   {
    "name": "rows",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 10,
    "min": 1,
    "description": "The amount of rows in the grid.",
    "widget": "int"
   },
   {
    "name": "width",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 300,
    "description": "The total width of the grid.",
    "widget": "float"
   },
   {
    "name": "height",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 300,
    "description": "The total height of the grid.",
    "widget": "float"
   },
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The center point of the grid.",
    "widget": "point"
   }
  ]
 },
 {
  "id": "corevector.group",
  "name": "group",
  "category": "corevector",
  "description": "Combine multiple geometries together.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/group",
  "ports": [
   {
    "name": "shapes",
    "type": "shape",
    "n3Type": "geometry",
    "range": "list",
    "description": "The list of shapes to group."
   }
  ]
 },
 {
  "id": "corevector.import_svg",
  "name": "import_svg",
  "category": "corevector",
  "description": "Import geometry from a SVG file.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/import_svg",
  "ports": [
   {
    "name": "file",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "",
    "description": "The SVG file to import.",
    "widget": "file"
   },
   {
    "name": "centered",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": true,
    "description": "If true, centers the shape around the position.",
    "widget": "toggle"
   },
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The target position of the shape.",
    "widget": "point"
   }
  ]
 },
 {
  "id": "corevector.line",
  "name": "line",
  "category": "corevector",
  "description": "Create a line between two points.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/line",
  "ports": [
   {
    "name": "point1",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "label": "Point 1",
    "description": "The starting point of the line.",
    "widget": "point"
   },
   {
    "name": "point2",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 100,
     "y": 100
    },
    "label": "Point 2",
    "description": "The ending point of the line.",
    "widget": "point"
   },
   {
    "name": "points",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 2,
    "min": 2,
    "description": "The amount of points to generate along the line.",
    "widget": "int"
   }
  ]
 },
 {
  "id": "corevector.line_angle",
  "name": "line_angle",
  "category": "corevector",
  "description": "Create a line between one point and an angle + distance.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/lineAngle",
  "ports": [
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The starting point of the line.",
    "widget": "point"
   },
   {
    "name": "angle",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "description": "The direction of the line.",
    "widget": "float"
   },
   {
    "name": "distance",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "description": "The distance between starting and ending point.",
    "widget": "float"
   },
   {
    "name": "points",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 2,
    "min": 2,
    "description": "The amount of points to generate along the line.",
    "widget": "int"
   }
  ]
 },
 {
  "id": "corevector.link",
  "name": "link",
  "category": "corevector",
  "description": "Generate a visual link between two shapes.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/link",
  "ports": [
   {
    "name": "shape1",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The first bounding volume of the link shape."
   },
   {
    "name": "shape2",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The second bounding volume of the link."
   },
   {
    "name": "orientation",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "horizontal",
    "description": "The direction of the link shape.",
    "widget": "menu",
    "menu": [
     {
      "key": "horizontal",
      "label": "Horizontal"
     },
     {
      "key": "vertical",
      "label": "Vertical"
     }
    ]
   }
  ]
 },
 {
  "id": "corevector.make_point",
  "name": "make_point",
  "category": "corevector",
  "description": "Create a point from X/Y coordinates.",
  "outputType": "point",
  "outputRange": "value",
  "fn": "corevector/makePoint",
  "ports": [
   {
    "name": "x",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "description": "The X position of the point.",
    "widget": "float"
   },
   {
    "name": "y",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "description": "The Y position of the point.",
    "widget": "float"
   }
  ]
 },
 {
  "id": "corevector.null",
  "name": "null",
  "category": "corevector",
  "description": "Do nothing.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/doNothing",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   }
  ]
 },
 {
  "id": "corevector.point",
  "name": "point",
  "category": "corevector",
  "description": "Create a point value that can be used as a variable.",
  "outputType": "point",
  "outputRange": "value",
  "fn": "corevector/point",
  "ports": [
   {
    "name": "value",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The input point.",
    "widget": "point"
   }
  ]
 },
 {
  "id": "corevector.point_on_path",
  "name": "point_on_path",
  "category": "corevector",
  "description": "Calculate a point on a path.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/pointOnPath",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "t",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "description": "The relative position on the shape (0 - 100).",
    "widget": "float"
   }
  ]
 },
 {
  "id": "corevector.polygon",
  "name": "polygon",
  "category": "corevector",
  "description": "Create a multi-sided polygon.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/polygon",
  "ports": [
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The center point of the polygon.",
    "widget": "point"
   },
   {
    "name": "radius",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "min": 0,
    "description": "The size of the polygon.",
    "widget": "float"
   },
   {
    "name": "sides",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 3,
    "min": 3,
    "description": "The number of sides the polygon has.",
    "widget": "int"
   },
   {
    "name": "align",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": false,
    "description": "If true, aligns the polygon to the X axis.",
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "corevector.quad_curve",
  "name": "quad_curve",
  "category": "corevector",
  "description": "Create a quadratic curve with one off-curve point.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/quad_curve",
  "ports": [
   {
    "name": "point1",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "label": "Point 1",
    "description": "The starting point.",
    "widget": "point"
   },
   {
    "name": "point2",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 100,
     "y": 0
    },
    "label": "Point 2",
    "description": "The ending point.",
    "widget": "point"
   },
   {
    "name": "t",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 50,
    "description": "The position of the off-curve point (0 - 100).",
    "widget": "float"
   },
   {
    "name": "distance",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 50,
    "description": "The offset of the curve from a straight line.",
    "widget": "float"
   }
  ]
 },
 {
  "id": "corevector.rect",
  "name": "rect",
  "category": "corevector",
  "description": "Create a rectangle, square or rounded rectangle.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/rect",
  "ports": [
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The center point of the rectangle.",
    "widget": "point"
   },
   {
    "name": "width",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "description": "The width of the rectangle.",
    "widget": "float"
   },
   {
    "name": "height",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "description": "The height of the rectangle.",
    "widget": "float"
   },
   {
    "name": "roundness",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The roundness of the rectangle.",
    "widget": "point"
   }
  ]
 },
 {
  "id": "corevector.reflect",
  "name": "reflect",
  "category": "corevector",
  "description": "Mirror the geometry around an invisible axis.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/reflect",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The center point of the mirror operation.",
    "widget": "point"
   },
   {
    "name": "angle",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 120,
    "description": "The angle at which to mirror the shape.",
    "widget": "float"
   },
   {
    "name": "keep_original",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": true,
    "description": "If true, also retains the original geometry.",
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "corevector.resample",
  "name": "resample",
  "category": "corevector",
  "description": "Distribute points along a shape.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/resample",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "method",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "length",
    "description": "The method of distribution.",
    "widget": "menu",
    "menu": [
     {
      "key": "length",
      "label": "By length"
     },
     {
      "key": "amount",
      "label": "By amount"
     }
    ]
   },
   {
    "name": "length",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 10,
    "min": 1,
    "description": "The maximum length of each segment.",
    "widget": "float"
   },
   {
    "name": "points",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 10,
    "min": 1,
    "description": "The amount of output points.",
    "widget": "int"
   },
   {
    "name": "per_contour",
    "type": "boolean",
    "n3Type": "boolean",
    "range": "value",
    "value": false,
    "description": "If true, the given amount is per contour, not for the whole path.",
    "widget": "toggle"
   }
  ]
 },
 {
  "id": "corevector.rotate",
  "name": "rotate",
  "category": "corevector",
  "description": "Rotate the shape according to the given angle.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/rotate",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "angle",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "description": "The rotation angle (in degrees).",
    "widget": "float"
   },
   {
    "name": "origin",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The point around which to rotate.",
    "widget": "point"
   }
  ]
 },
 {
  "id": "corevector.round_segments",
  "name": "round_segments",
  "category": "corevector",
  "description": "Transform the straight corners of a shape into curvy ones.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/round_segments",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "d",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 10,
    "description": "The distance from the control points to the corner point.",
    "widget": "float"
   }
  ]
 },
 {
  "id": "corevector.scale",
  "name": "scale",
  "category": "corevector",
  "description": "Resize the shape by scaling it.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/scale",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "scale",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 100,
     "y": 100
    },
    "description": "The scale factor.",
    "widget": "point"
   },
   {
    "name": "origin",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The point around which to scale.",
    "widget": "point"
   }
  ]
 },
 {
  "id": "corevector.scatter",
  "name": "scatter",
  "category": "corevector",
  "description": "Generate points within the boundaries of a shape.",
  "outputType": "point",
  "outputRange": "list",
  "fn": "pyvector/scatter",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "amount",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 20,
    "min": 0,
    "description": "The amount of output points to generate.",
    "widget": "int"
   },
   {
    "name": "seed",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "description": "The random variation.",
    "widget": "int"
   }
  ]
 },
 {
  "id": "corevector.shape_on_path",
  "name": "shape_on_path",
  "category": "corevector",
  "description": "Copies shapes on a path.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "pyvector/shape_on_path",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "list",
    "description": "The shape(s) to copy."
   },
   {
    "name": "path",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The path on which to copy the shape(s)."
   },
   {
    "name": "amount",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 1,
    "min": 0,
    "description": "The amount of copies.",
    "widget": "int"
   },
   {
    "name": "alignment",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "leading",
    "description": "The way to lay out the shapes horizontally.",
    "widget": "menu",
    "menu": [
     {
      "key": "leading",
      "label": "Leading"
     },
     {
      "key": "trailing",
      "label": "Trailing"
     },
     {
      "key": "distributed",
      "label": "Distributed"
     }
    ]
   },
   {
    "name": "spacing",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 20,
    "min": 0,
    "description": "The spacing between the shapes.",
    "widget": "float"
   },
   {
    "name": "margin",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "min": 0,
    "description": "Empty space before and/or after the shapes.",
    "widget": "float"
   },
   {
    "name": "baseline_offset",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "description": "The vertical offset of the shapes from the baseline.",
    "widget": "float"
   }
  ]
 },
 {
  "id": "corevector.skew",
  "name": "skew",
  "category": "corevector",
  "description": "Skew the shape.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/skew",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "skew",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The skew factor.",
    "widget": "point"
   },
   {
    "name": "origin",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The point around which to skew.",
    "widget": "point"
   }
  ]
 },
 {
  "id": "corevector.snap",
  "name": "snap",
  "category": "corevector",
  "description": "Snap geometry to a grid.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/snap",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "distance",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 10,
    "min": 1,
    "description": "The size of the grid cells.",
    "widget": "float"
   },
   {
    "name": "strength",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "min": 0,
    "max": 100,
    "description": "The strength of attraction to the grid (0=no influence, 100=all points are strictly on the grid).",
    "widget": "float"
   },
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The position of the grid.",
    "widget": "point"
   }
  ]
 },
 {
  "id": "corevector.sort",
  "name": "sort",
  "category": "corevector",
  "description": "Sort points or shapes using different sorting methods.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "pyvector/sort",
  "ports": [
   {
    "name": "shapes",
    "type": "shape",
    "n3Type": "geometry",
    "range": "list",
    "description": "The list of shapes to sort."
   },
   {
    "name": "order_by",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "none",
    "description": "The sort method.",
    "widget": "menu",
    "menu": [
     {
      "key": "none",
      "label": "No Change"
     },
     {
      "key": "x",
      "label": "X"
     },
     {
      "key": "y",
      "label": "Y"
     },
     {
      "key": "angle",
      "label": "Angle to Point"
     },
     {
      "key": "distance",
      "label": "Distance to Point"
     }
    ]
   },
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The center point.",
    "widget": "point"
   }
  ]
 },
 {
  "id": "corevector.stack",
  "name": "stack",
  "category": "corevector",
  "description": "Arrange shapes in a horizontal or vertical layout.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "pyvector/stack",
  "ports": [
   {
    "name": "shapes",
    "type": "shape",
    "n3Type": "geometry",
    "range": "list"
   },
   {
    "name": "direction",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "e",
    "widget": "menu",
    "menu": [
     {
      "key": "n",
      "label": "North"
     },
     {
      "key": "e",
      "label": "East"
     },
     {
      "key": "s",
      "label": "South"
     },
     {
      "key": "w",
      "label": "West"
     }
    ]
   },
   {
    "name": "margin",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 5,
    "widget": "float"
   }
  ]
 },
 {
  "id": "corevector.star",
  "name": "star",
  "category": "corevector",
  "description": "Create a star shape.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/star",
  "ports": [
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The center point of the star.",
    "widget": "point"
   },
   {
    "name": "points",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 20,
    "min": 1,
    "description": "The amount of points in the star.",
    "widget": "int"
   },
   {
    "name": "outer",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 200,
    "label": "Outer Diameter",
    "description": "The outer diameter of the star.",
    "widget": "float"
   },
   {
    "name": "inner",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 100,
    "label": "Inner Diameter",
    "description": "The inner diameter of the star.",
    "widget": "float"
   }
  ]
 },
 {
  "id": "corevector.text_on_path",
  "name": "text_on_path",
  "category": "corevector",
  "description": "Create a text path that follows a shape.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/text_on_path",
  "ports": [
   {
    "name": "text",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "text following a path",
    "description": "The input text.",
    "widget": "string"
   },
   {
    "name": "path",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The path on which to put the text."
   },
   {
    "name": "font_name",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "Verdana",
    "description": "The name of the font.",
    "widget": "font"
   },
   {
    "name": "font_size",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 24,
    "description": "The size of the font.",
    "widget": "float"
   },
   {
    "name": "alignment",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "leading",
    "description": "The way to lay out the text horizontally.",
    "widget": "menu",
    "menu": [
     {
      "key": "leading",
      "label": "Leading"
     },
     {
      "key": "trailing",
      "label": "Trailing"
     }
    ]
   },
   {
    "name": "margin",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "description": "The relative position of the text on the path (0 - 100).",
    "widget": "float"
   },
   {
    "name": "baseline_offset",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "description": "The vertical offset of the text from the path.",
    "widget": "float"
   }
  ]
 },
 {
  "id": "corevector.textpath",
  "name": "textpath",
  "category": "corevector",
  "description": "Create a path out of text.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "corevector/textpath",
  "ports": [
   {
    "name": "text",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "hello",
    "description": "The input text.",
    "widget": "string"
   },
   {
    "name": "font_name",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "Verdana",
    "description": "The name of the font.",
    "widget": "font"
   },
   {
    "name": "font_size",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 24,
    "description": "The size of the font.",
    "widget": "float"
   },
   {
    "name": "align",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "CENTER",
    "description": "The alignment of the text.",
    "widget": "menu",
    "menu": [
     {
      "key": "LEFT",
      "label": "Left"
     },
     {
      "key": "CENTER",
      "label": "Center"
     },
     {
      "key": "RIGHT",
      "label": "Right"
     },
     {
      "key": "JUSTIFY",
      "label": "Justify"
     }
    ]
   },
   {
    "name": "position",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The center point of the text.",
    "widget": "point"
   },
   {
    "name": "width",
    "type": "float",
    "n3Type": "float",
    "range": "value",
    "value": 0,
    "min": 0,
    "description": "The maximum width of the text.",
    "widget": "float"
   }
  ]
 },
 {
  "id": "corevector.translate",
  "name": "translate",
  "category": "corevector",
  "description": "Move the shape, changing its position.",
  "outputType": "shape",
  "outputRange": "value",
  "fn": "pyvector/translate",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "translate",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 0,
     "y": 0
    },
    "description": "The amount of translation.",
    "widget": "point"
   }
  ]
 },
 {
  "id": "corevector.ungroup",
  "name": "ungroup",
  "category": "corevector",
  "description": "Decompose the input geometry into its paths.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "corevector/ungroup",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   }
  ]
 },
 {
  "id": "corevector.wiggle",
  "name": "wiggle",
  "category": "corevector",
  "description": "Shift points by a random amount.",
  "outputType": "shape",
  "outputRange": "list",
  "fn": "pyvector/wiggle",
  "ports": [
   {
    "name": "shape",
    "type": "shape",
    "n3Type": "geometry",
    "range": "value",
    "description": "The input shape."
   },
   {
    "name": "scope",
    "type": "string",
    "n3Type": "string",
    "range": "value",
    "value": "points",
    "description": "The type of objects to wiggle: points, contour or paths.",
    "widget": "menu",
    "menu": [
     {
      "key": "points",
      "label": "Points"
     },
     {
      "key": "contours",
      "label": "Contours"
     },
     {
      "key": "paths",
      "label": "Paths"
     }
    ]
   },
   {
    "name": "offset",
    "type": "point",
    "n3Type": "point",
    "range": "value",
    "value": {
     "x": 10,
     "y": 10
    },
    "description": "The maximum amount of translation.",
    "widget": "point"
   },
   {
    "name": "seed",
    "type": "int",
    "n3Type": "int",
    "range": "value",
    "value": 0,
    "description": "The random variation.",
    "widget": "int"
   }
  ]
 }
];
